version: "3"
services:
  dev-server:
    container_name: dev-server
    build: 
      context: ./
      dockerfile: ./dockerfiles/server/dev/Dockerfile
    volumes:
      - .:/home/node/app
      - node_modules_volume:/home/node/app/node_modules
    networks: 
      - widevine-network
    tty: true
    ports:
      - 127.0.0.1:3000:8080 

  production-server:
    container_name: production-server
    build: 
      context: ./
      dockerfile: ./dockerfiles/server/production/Dockerfile
    tty: true
    ports:
      - 127.0.0.1:8080:8080 


volumes:
  node_modules_volume:

networks:
  widevine-network: